apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-cicd-demo
  template:
    metadata:
      labels:
        app: devops-cicd-demo
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devops-cicd-demo
          image: crpi-pleclmjo9htj5t3x.cn-hangzhou.personal.cr.aliyuncs.com/devops-cicd-demo/devops-cicd-demo:1956bfddb6241df34ee3759f4458e87e46c3cc3c
          imagePullPolicy: Always
          env:
          - name: ENV_NAME
            value: "dev"
          ports:
            - containerPort: 5000