apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-cicd-demo
  template:
    metadata:
      labels:
        app: devops-cicd-demo
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devops-cicd-demo
          image: crpi-pleclmjo9htj5t3x.cn-hangzhou.personal.cr.aliyuncs.com/devops-cicd-demo/devops-cicd-demo:dee63edae1dbfe1e91ae0e7be4bcbe4a761ced38
          imagePullPolicy: Always
          ports:
            - containerPort: 5000