apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-demo
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-demo
  template:
    metadata:
      labels:
        app: devops-cicd-demo
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devops-cicd-demo
          image: crpi-pleclmjo9htj5t3x.cn-hangzhou.personal.cr.aliyuncs.com/devops-cicd-demo/devops-cicd-demo:2579a99aa207a0308d8f27e25a1b5bc5fa91578c
          imagePullPolicy: Always
          env:
          - name: ENV_NAME
            valueFrom:
              configMapKeyRef:
                name: devops-cicd-demo-config
                key: ENV_NAME
          ports:
            - containerPort: 5000