apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-demo
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-demo
  template:
    metadata:
      labels:
        app: devops-cicd-demo
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devops-cicd-demo
          image: crpi-pleclmjo9htj5t3x.cn-hangzhou.personal.cr.aliyuncs.com/devops-cicd-demo/devops-cicd-demo:47ab4837705c98f9453e58283e1d5fe4ca1c3cf3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000